### ISSUE TITLE
Tax calculator result going out of the box on mobile

### ISSUE THREAD

**Issue by NeeleshGajare** [mitheelgajare/commercial-math-calculator#8]
**Describe the bug**
Tax calculator result going out of the box when using the website on mobile. 
Need to set some decimal precision.

**To Reproduce**
1. Go to the website
2. Scroll down to discount calculator 
3. Enter price after discount as 200
4. Set gst as 28 %
5. check the result box

**Expected behavior**
The result should fit into the result box

**Screenshots**
![Screenshot_20211030-184713_Chrome](https://user-images.githubusercontent.com/93050465/139534461-8b758254-1ba5-47b3-a57a-d38604d9489f.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] samsung m31s
 - OS: [e.g. iOS8.1]  Android
 - Browser [e.g. stock browser, safari] chrome
 - Version [e.g. 22] NA

**Comment by mitheelgajare** [comment]
Thank you for raising an issue!
@NeeleshGajare would you like to work on this issue? If yes, I can assign you.

**Comment by NeeleshGajare** [comment]
Yes please

**Comment by mitheelgajare** [comment]
@NeeleshGajare Hi. I just wanted to know how long would it take to resolve this issue 😊

**Comment by NeeleshGajare** [comment]
I am going to try it tomorrow,  if time permits.
Thanks for the reminder 😀
